# Generated by Django 5.2.2 on 2025-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='current_uses',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
