# Generated by Django 5.2.2 on 2025-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_alter_shortenedurl_current_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
